### ISSUE TITLE
Bug in test to whitelist values

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#104]
I should have rebased #74 before merging 😅 

https://github.com/Sage-Bionetworks/dccvalidator/blob/bd833f865e40fdd9dfcacdb8340d9bb53c1c16c5/tests/testthat/test-check-annotation-values.R#L392-L402

**Comment by karawoo** [comment]
@Aryllen could you look into this one? It's an issue of the coercion and whitelisting interfering with one another I believe.

**Comment by Aryllen** [comment]
Will do.
