### ISSUE TITLE
Track User Feedback

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#111]
It would be beneficial to the end user to provide them a mechanism in the app where they can: 

1. file bugs
2. request new annotation keys or values
3. provide general feedback

**Comment by karawoo** [comment]
Do you think adding a footer with a link to our GitHub issues + contact info for us would work? Or do you have something else in mind?

**Comment by kelshmo** [comment]
A footer in the app itself? I do agree pointing to GitHub issues + email to appropriate Sage admin synapse team is the best approach.

**Comment by karawoo** [comment]
Yes, in the app

**Comment by Aryllen** [comment]
It might be good to specify what types of feedback/bugs/questions to report to which place. If they are having an app related issues or have app related feedback, then go to GitHub issues. If they are having more personalized problems, such as questions on how to use the app or they don't understand why their specific data won't pass validation, then ask via email.
