### ISSUE TITLE
Boolean and Numerics Invalid

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#118]
Too bad there is not issue tracking on forks....

@cw-dvr8 is returning an error when she passes values that *should be* acceptable. 
![individual_human_pass](https://user-images.githubusercontent.com/40647130/67023651-ff096d00-f0b7-11e9-9ede-0485bbbce8e2.jpg)

- Types are codified in the app [here](https://github.com/kelshmo/dccvalidator/blob/master/R/check-annotation-values.R#L188-L194).
1. boolean values that are failing in this case are [here](https://www.synapse.org/#!Synapse:syn20981788/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIwOTgxNzg4IHdoZXJlIGtleSBpbiAoJ2RlbWVudGlhJywgJ1BNSUNlcnRhaW4nKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=) in the PEC Annotations table. 
- I'm not exactly sure what the app is expecting. Part of the problem could be a missing columnType for `PMICertain`
```
> values <- c("TRUE", "FALSE")
> can_coerce(values, "logical")
[1] FALSE
> can_coerce(values, "character")
[1] FALSE
> values <- c("True", "False")
> can_coerce(values, "logical")
[1] FALSE
> can_coerce(values, "character")
[1] FALSE
```
2.  numeric values that are failing in this case are [here](https://www.synapse.org/#!Synapse:syn20981788/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIwOTgxNzg4IHdoZXJlIGtleSBpbiAoJ2FnZU9uc2V0JywgJ2FnZU9mRGVhdGgnLCdvcmdhblJJTicpIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==) in the PEC Annotations table.  

Doing some debugging now, but feedback welcome.

**Comment by karawoo** [comment]
If there are enumerated values for a key, then validation only checks the given values against the enumerated values. `check_type()` and therefore `can_coerce()` don't apply. The booleans are failing because they don't match the allowable values of "True" and "False" (capitalized) in your PEC Annotations table.

The numerics should be ok, are you sure they are not stored as strings in the data file?

**Comment by cw-dvr8** [comment]
I compared the "failedQC" key on the AMP-AD table to the "dementia" key on the PEC table, and they both are defined as Booleans with the values "True" and "False".  The only difference I see is that on the AMP-AD table the columnType is "BOOLEAN" and on the PEC table it's "boolean".  Is the code case sensitive?  Could also explain why the PEC validator is not liking the numbers ("NUMBER" vs. "number").

**Comment by karawoo** [comment]
The columnType does not matter when there are enumerated values in the annotations table. `check_annotation_values()` checks the data against enumerated values if there are any, and only checks the type if no enumerated values are specified. Your data does not match the enumerated values: your data says "true" and "false" while your annotation dictionary requires "True" or "False".

Without access to your data I do not know why the numerics aren't working. My guess is that they are stored as strings in the data file. If you can provide a reproducible example I can look into it. The example below seems to work as expected using @kelshmo's fork of the package:

``` r
#> devtools::install_github("kelshmo/dccvalidator")
library("dccvalidator")
#> Loading required package: shinyBS
library("syndccutils")
library("synapser")
#> 
#> TERMS OF USE NOTICE:
#>   When using Synapse, remember that the terms and conditions of use require that you:
#>   1) Attribute data contributors when discussing these data or results from these data.
#>   2) Not discriminate, identify, or recontact individuals or groups represented by the data.
#>   3) Use and contribute only data de-identified to HIPAA standards.
#>   4) Redistribute data only under these same terms of use.

# Create data
dat <- data.frame(
  ageOnset = c(3, 3),
  ageOfDeath = c(23, 47),
  organRIN = c(34, 34)
)

synLogin()
#> Welcome, Kara Woo!
#> NULL
annotations <- get_synapse_annotations(synID = "syn20981788")
#>  [####################]100.00%   1/1   Done...    Downloading  [####################]100.00%   117.6kB/117.6kB (475.6kB/s) Job-98505008980066133037911246.csv Done...
check_annotation_values(dat, annotations)
#> <check_pass: All annotation values are valid>
```

<sup>Created on 2019-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cw-dvr8** [comment]
Attaching my test file.

**Comment by karawoo** [comment]
Your attachment does not come through on the GitHub issue.

**Comment by karawoo** [comment]
Looking at the test data you sent, the values in these columns are read in as integers, not numeric. I think the best way to solve this is to treat integers as coercible to numeric in `can_coerce()`.

**Comment by cw-dvr8** [comment]
For clarification, synapseAnnotation_master.jpeg is what is currently in the synapseAnnotations master branch for "failedQC".  AnnotationsModules_Synapse.jpeg is what is in the Annotations Modules table on Synapse.  The case of "true" and "false" is different between the two.  Does this mean that we need to tell the users to follow the convention that's used on Synapse?  I can tweak the code to print that out in the dictionary from the schema, but I want to confirm it first.

![synapseAnnotation_master](https://user-images.githubusercontent.com/20506821/67050301-0eef7400-f0ed-11e9-9d98-7a5c64a9537e.jpg)
![AnnotationModules_Synapse](https://user-images.githubusercontent.com/20506821/67050315-144cbe80-f0ed-11e9-8645-1971dd1a4c33.jpg)

**Comment by karawoo** [comment]
Argh. [annotator](https://github.com/Sage-Bionetworks/annotator) is changing the enumerated values from what's in synapseAnnotations. @kdaily I'm curious your thoughts on this, should we update annotator to keep booleans as lower case `true` and `false` as is in the annotations? Right now it's converting them to Python booleans, which are different from both synapse booleans and R booleans 😬

**Comment by cw-dvr8** [comment]
Since the PEC validator uses a different table than the AMP-AD validator, I'm going to convert the Boolean values in the table into lower case strings (true/false) in order to be consistent with the base schema.

**Comment by karawoo** [comment]
@cw-dvr8 that seems like a good call in the meantime. We can sort out the broader synapseAnnotations issue separately. Thanks for catching this.

**Comment by karawoo** [comment]
Opened an issue on annotator for the boolean part: https://github.com/Sage-Bionetworks/annotator/issues/91

**Comment by kelshmo** [comment]
`can_coerce()` deals with the numeric failures and I verified the changes to values in the PEC annotations table (tested in @cw-dvr8 [sandbox](https://www.synapse.org/#!Synapse:syn21022441/tables/)) deal with the boolean failure. Cindy, can you update the [PEC Annotations table](https://www.synapse.org/#!Synapse:syn20981788/tables/) and then close this issue?  Thanks.
