### ISSUE TITLE
Complete required columns check is wrong for drosophila metadata

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#136]
Currently requiring individualID and biospecimenID in the biospecimen metadata. However, there is no individualID for drosophila metadata.

Some options:
1) Make a more complicated config file that tailors required columns by template.
2) Make some other check in the R code that tailors required columns in config file by template.
3) Change `check_cols_complete` to only check required columns that exist in the data.

**Comment by karawoo** [comment]
I think 3 is the simplest and easiest to maintain. What do you think?

**Comment by Aryllen** [comment]
I agree. The success message of "all required columns are complete" is a little misleading, but we could change it to "all required columns present are complete". Overall, it's probably not a big deal for the success message to be off as much as it is to not fail when it shouldn't.
