### ISSUE TITLE
Change 'Upload Complete' indicator on fileInputs

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#151]
The `fileInput` gives a status that shows `Upload Complete` after giving it a file. This only uploads to a temp file on the server, though. The `Submit` or `Validate` button is what uploads the data to Synapse. By having the `Upload Complete` on the `fileInput`, it makes it look like the user does not need to press the `Submit` button in Documentation. It might also be a little confusing in the Validator.

https://stackoverflow.com/questions/40620176/getting-rid-of-the-status-bar-in-file-upload-in-shiny

**Comment by Aryllen** [comment]
On this one, should we simply change the text that prints or remove the progress bar altogether? Personally, I like the progress bar since it sometimes takes a second to upload the file to a temp directory. If the `submit` or `validate` buttons are pressed before it's fully uploaded, it _should_ give an error (I've not checked since it's almost always fast enough for response time, but theoretically it's possible).

If we simply change the text, what should we change it to? "File ready to submit/validate?"

**Comment by kelshmo** [comment]
I like the progress bar - it is nice to receive visual feedback that something is happening. I like "File ready to validate." - to match the Validate button.

**Comment by Aryllen** [comment]
From searching, it seems like the progress bar text can only be changed via javascript. I found this, which is helpful: https://stackoverflow.com/questions/47053705/shiny-change-upload-complete-and-files-text-in-fileinput.

I don't know javascript, so I'm looking into it to see if I can specify different reactions for the validator fileInput progress bars versus the documentation progress bars. Then we could have "File ready to validate" on one set and "File ready to submit" on the other set since "validate" might be confusing for both. If not, we could just change it to "File ready", but that is vague.

**Comment by Aryllen** [comment]
The link I found earlier has not been helpful. I can't even get the example to run locally correctly. 

Another challenge is that the documentation fileInputs are within a module so we have to somehow make sure the Javascript knows the correct ids.

If anyone has more experience with Javascript, feel free to take a stab at this. Note: we could use [shinyjs](https://www.rdocumentation.org/packages/shinyjs/versions/1.0/topics/extendShinyjs), which makes a function for calling the custom JS script, but it still comes back to being competent at Javascript and getting ids correct.

**Comment by karawoo** [comment]
Ok, thanks @Aryllen! It's not a high priority, so we can come back to this later.
