### ISSUE TITLE
Check for invalid Synapse study names

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#152]
A user during the Bug Bash session said, "Putting an invalid Synapse name in Study name shows Synapse 400 error."

Since the study name is appended to the front of the documentation filenames, it has to be something that is valid within a Synapse filename.

**Comment by Aryllen** [comment]
It looks like the studies that currently exist have these special characters:
- period
- hyphen
- underscore

I can check for other special characters and flag it as an error. Are there any other special characters I should not flag? (note: a single space appears to be fine, but not sure if we want to allow those or would even give a name with that in it.)

**Comment by kelshmo** [comment]
We have a few cases of study names with spaces. I think I am OK with names having spaces.

**Comment by Aryllen** [comment]
How is this for the error message?

![image](https://user-images.githubusercontent.com/25048342/67802052-b488d880-fa47-11e9-8530-ec7f8cb8035c.png)

**Comment by karawoo** [comment]
I'd suggest using the same requirements as Synapse does: "Names may only contain: letters, numbers, spaces, underscores, hypens [sic], periods, plus signs, and parentheses"

**Comment by Aryllen** [comment]
Alrighty. Sounds good.

**Comment by karawoo** [comment]
(we should spell "hyphens" correctly though)

**Comment by Aryllen** [comment]
Note that the PR #171 does not address issues with filenames themselves. It is still currently assumed that if the Shiny app will upload the file to the temp directory, then Synapse should accept the name as it is. We can open a separate issue if we think this will be a problem.
