### ISSUE TITLE
Add notes about file requirements

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#159]
Copy/pasted from Bug Bash document due to being multiple things.

> Add a note about study and assay description file format (mette)
> In addition to the above a limit to the file size 
> And, file name: Names may only contain: letters, numbers, spaces, underscores, hypens, periods, plus signs, and parentheses

Not completely sure if some of these things would/should only refer to documentation files or for all files.

**Comment by karawoo** [comment]
We can accept many file formats for documentation: .docx, .txt., .md, so I'm not sure we want constrain the upload to all the possible ones, but we could give a hint about preferred formats in the label next to the box, e.g. "Upload the study description file (.docx or .txt)".

**Comment by Aryllen** [comment]
I'm concerned that the users may think that they could **only** upload .docx or .txt if we put that in the label.

**Comment by Aryllen** [comment]
> And, file name: Names may only contain: letters, numbers, spaces, underscores, hypens, periods, plus signs, and parentheses

This is taken care of in PR #171 for study documentation upload, but only in that it checks the study name given would not invalidate the full filename once prepended. Still would need to validate filenames if we think Shiny will actually upload a file that has a bad filename. I'm not sure how to test this since the files that are valid filenames on my computer are also valid filenames for Synapse. Windows won't allow me to have crazy filenames.

> In addition to the above a limit to the file size 

What would be the file size limit? Most files should be small, unless they were adding HQ images. We could limit the file types to .txt, .docx, .md, and .tex, which would remove any odd file uploads.

**Comment by karawoo** [comment]
I don't think we need to limit file sizes. Limiting the file types to the ones you suggested sounds fine to me. I do think we should also check the file names the way we do for study names.

**Comment by Aryllen** [comment]
Sounds good.
