### ISSUE TITLE
Include process instructions

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#161]
Copy/pasted from Bug Bash document.
>Include language that describes the process going from submitting study and assay documentation to submitting manifest and metadata files. Could be at a button next to ‘Submit’ called ‘further instructions’, something like “contact ….. for information about manifest parent ID’

Mette will draft the suggested language.

**Comment by karawoo** [comment]
This may be sufficiently covered by the [vignette](https://sage-bionetworks.github.io/dccvalidator/articles/using-the-dccvalidator-app-amp-ad.html) but we can add some additional detail if needed.
