### ISSUE TITLE
Should something be listed as both a warning and failure?

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#162]
![image](https://user-images.githubusercontent.com/25048342/67709691-b08f8480-f97b-11e9-9a33-9959a32a848f.png)

These are two separate tests, one that just gives a warning for empty columns and the other gives a fail because `parent` is required to be complete.

**Comment by karawoo** [comment]
I'm wondering whether `check_cols_empty()` should only check the columns that aren't required to be complete. What do you think, @Aryllen?

**Comment by Aryllen** [comment]
We could do that pretty easily, I think, if we just passed in the required columns to `check_cols_empty()` and removed them from the check. That would definitely get rid of the warning/fail for ultimately the same problem.

**Comment by kelshmo** [comment]
good catch @Aryllen, I agree with only failing required columns and not passing a warning.

**Comment by Aryllen** [comment]
Thanks, @kelshmo, but I can't take credit for this one. This is one of the items that came up during our Bug Bash.
