### ISSUE TITLE
Logout not recognized unless page refreshed

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#164]
Copy/paste from Bug Bash document.
> If I log out of Synapse while in the App, the app does not recognize that I am logged out unless I refresh the page. I was still able to upload files under my user id before refreshing the page, even after logging out. I also have to refresh the page, if I login into Synapse in another tab

**Comment by karawoo** [comment]
This is expected behavior, but I imagine we could change it by querying for the session token at a regular interval. That might interfere with app performance, however.

**Comment by karawoo** [comment]
I'm going to close this as I think it's better left as-is.
