### ISSUE TITLE
Improve approach for retrieving annotations data

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#17]
Right now we package up the annotations data with the package in sysdata.rda. This means that the data could be out of date compared to what has been released on Synapse (and even if we keep the data up to date, people will need to reinstall dccvalidator every time the data changes). We should pull the data directly from Synapse when possible, but I'd also like to avoid having to download it each time someone runs one of the checking functions. One possible option: 

* in `.onLoad()` try to download the annotations data
* if this fails (i.e. can't log in to synapse), fall back to prepackaged data with a message/warning
* provide another function that people can use if they want to get access to the newest data (`load_annotations()` or similar). Ideally this would replace the prepackaged data within the package environment so nothing else needs to be changed (or else we can create a separate new environment for both the prepackaged and direct-downloaded data -- might be easier to modify that environment).

Need to think through potential consequences of this approach as it seems a bit atypical. If we do this, synapser should go in Depends instead of Imports.

**Comment by karawoo** [comment]
Thinking more about this, I think the best approach is:
1. Add an argument to the annotation checking functions that lets user provide the annotation data frame
2. If no annotation data frame is provided, fall back to `get_synapse_annotations()` (requires being logged in)

Thus the typical flow for the user would be, for example (using a file view):

```r
synLogin()
annots <- get_synapse_annotations()
fv <- synTableQuery("SELECT * FROM syn17020234")
check_annotation_keys(fv, annots)
check_annotation_values(fv, annots)
```

But this is also a possibility:

```r
synLogin()
fv <- synTableQuery("SELECT * FROM syn17020234")
check_annotation_keys(fv) # if not given an annotations data frame, it pulls from synapse
check_annotation_values(fv)
```

This would also address #11, since users could subset the annotations or create their own data frame and pass it to the functions. @milen-sage are you ok with this approach?

**Comment by milen-sage** [comment]
Yes, that makes a lot of sense; perhaps we can still provide a utility function for the user that packages the annotations in a data frame format, if they choose to do that. They could work with this data frame to subset it as desired.

**Comment by karawoo** [comment]
Yes, I was thinking about reexporting the `get_synapse_annotations()` function from [syndccutils](https://github.com/Sage-Bionetworks/syndccutils); we could also provide something like a `cached_synapse_annotations()` function to provide a prepackaged dataset without needing to use Synapse at all...I guess the main use case for this would be working offline.
