### ISSUE TITLE
Pull study names from a parent synID

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#245]
Instead of manually maintaining a separate study table, could we consider pulling study names from folder names given a parent ID?

**Comment by karawoo** [comment]
I'm open to it. That would also (in AMP-AD) let us more easily filter the study names based on the species the user has selected, since we have separate parent folders for human and model studies.

**Comment by Aryllen** [comment]
Interesting idea. What would be a potential parent ID for AMP-AD that would give the study folder names we would need? I'm also wondering if it would add a lot of time on the get the names from folders versus grabbing a single table.

**Comment by karawoo** [comment]
syn5550382 for human studies, syn5550383 for model system studies. Those two are are children of syn5550376. Not sure if PEC follows a similar organization or not.

**Comment by kelshmo** [comment]
PEC follows the same organization. 

I was thinking something like: 
```
parentID <- "syn5553626"
children <- synapser::synGetChildren(parentID, includeTypes = list("folder"))$asList()
studies <- tibble::tibble(id = unlist(lapply(children, function(x) x$id))) %>% 
  mutate(study_names = unlist(lapply(children, function(x) x$name)))
```

**Comment by Aryllen** [comment]
I tried this out using synapser and it doesn't seem slow. We wouldn't need to keep both the folder IDs and names in a table, but rather just grab a list of the names.

dccvalidator doesn't use synapser, however. I tried doing this with reticulate + synapseclient and I'm stuck on how we get the children out of the python object.

**Comment by karawoo** [comment]
I think we might want `walk()` from the synapseutils python package: https://python-docs.synapse.org/build/html/synapseutils.html#module-synapseutils.walk

**Comment by kelshmo** [comment]
I ran a test with `walk()` but since is traverses the complete hierarchy, it would not only output the first level of study folder names, but all of the nested folder/file data.

**Comment by kelshmo** [comment]
Right - no more `synapser` :(

Here is a start, I would need to test more with `reticulate` to see how to better manipulate the output to play nice in R:
```
import synapseclient
syn = synapseclient.login(silent=True)
synId = "syn5553626"
f2 = syn.getChildren(parent = synId, includeTypes = ['folder'], sortBy='NAME')
for item in f2: 
	 print(item.get("name"))
```

**Comment by kelshmo** [comment]
The folder structure in PEC has changed; we do not have a single root folder for studies. Thus, this proposed solution is no longer relevant. @Aryllen re-open if you think this should be prioritized.

**Comment by Aryllen** [comment]
Thank you for closing this when it was no longer relevant, @kelshmo! If you have any other suggestions for better management of study names in the future, I'm all ears.
