### ISSUE TITLE
Better error message if annotations have multiple definitions

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#249]
A user reported being unable to validate a metadata file due to the following error: `EXPR must be length 1 vector`. This is due to this line, which assumes there should be one columnType per annotation key:

https://github.com/Sage-Bionetworks/dccvalidator/blob/b87dda9ebf841a672e3e4d06109a765983b01e43/R/check-annotation-values.R#L207

However now that in AMP-AD we are validating annotations AND non-annotations, it's easier to end up in a situation where the same key is defined differently in two places because they are maintained separately. I've added a [check](https://github.com/Sage-Bionetworks/AD-DCC/blob/39c32cb56afa8a87cd8b920c83d35f8a6c874080/add_template_description_sheets.R#L49) to the AMP-AD definitions to ensure we do not duplicate things in synapseAnnotations. However we  should probably also fail with a more informative message in `check_type()` if any duplicate definitions do occur.

**Comment by kelshmo** [comment]
Can you post an example use case? I want to make sure I understand the discrepancy between annotations and non-annotation definitions.

**Comment by karawoo** [comment]
I've fixed it now in the AMP-AD data dictionary, but we had pH defined once as a string (in synapseAnnotations) and once as numeric (in the AMP-AD dictionary), so the code in `check_type()` was trying to do

```r
switch(
    c("STRING", "DOUBLE"),
    "STRING" = "character",
    "BOOLEAN" = "logical",
    "INTEGER" = "integer",
    "DOUBLE" = "numeric"
  )
```

which throws an error.

**Comment by kelshmo** [comment]
Thanks for clarifying.
