### ISSUE TITLE
Warn about submitting a manifest as .csv

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#271]
A user tried to upload a manifest.csv to the validator and received the following error message (to the effect of): 

```
all the required columns are missing
invalid column: path.parent.individualID.specimenID.isMultiSpecimen.assay.fileFormat.consortium.study.grant.resourceType.dataType.dataSubtype.metadataType.analysisType
```
I don't believe it is possible to return any kind of message before the user selects *Validate*. Therefore, if the user inputs an incorrect file format, the app can return a failure.

**Comment by kelshmo** [comment]
It looks like on a mac the file type is reflected in the files available to "Browse" but this is not the case across all systems. 

https://github.com/Sage-Bionetworks/dccvalidator/blob/9de07eaf43d14b5dc42ddfd74213f76a429cdcf9/R/app-ui.R#L114-L123

**Comment by Aryllen** [comment]
Here's a snippet of what I see on Windows. I can click on "All Files" in the drop-down. Then it will show me all files in the folder, regardless of type. It doesn't block me from choosing an incorrect file type at all.

![image](https://user-images.githubusercontent.com/25048342/73573074-4deccf80-4427-11ea-9207-7520e270a1d1.png)

**Comment by karawoo** [comment]
Yeah, the `accept` attribute in HTML is more of a hint than a binding rule, and different systems and browsers support it in different ways.

**Comment by kelshmo** [comment]
Can we add a check that displays a failure if a user uploads a .csv manifest?

**Comment by karawoo** [comment]
Yeah that's doable, especially if we're ok with just basing it off the file extension. That won't be 100% reliable, but I'd guess it will capture most cases.
