### ISSUE TITLE
Nicer file summary from dccmonitor 

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#281]
@Aryllen would you be open to contributing the file summary you created for dccmonitor (the one that appears below the visdat graph when you view the data summary) to dccvalidator? We could then use it in the dccvalidator app, and export it so it can also be used in dccmonitor as well (can't be the other way around or we'll create a circular dependency between the two packages). It looks so much better, and is much more useful than our current summary.

**Comment by Aryllen** [comment]
For sure! I will be asking for help on one part for that (in person because it's hard to explain in text), but I can definitely add the file summary to dccvalidator.
