### ISSUE TITLE
Switch to OAuth

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#292]
I have not heard the status of Synapse OAuth support lately, but if it is at a point now where users can authenticate and upload data, we should use it in place of the session token cookie. This would indirectly fix #290, hopefully.

**Comment by Aryllen** [comment]
OAuth is now possible. Refer to Tom's example [here](https://github.com/Sage-Bionetworks/SynapseShinyApp/tree/update-reticulate).
