### ISSUE TITLE
Rename "documentation upload" header in AMP-AD documentation

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#296]
It is confusing and leads people to upload metadata to the documentation tab 😬

**Comment by Aryllen** [comment]
The documentation tab doesn't discuss what the Documentation tab is for. It might be good to leave the header there, but add content to briefly describe what that is used for and what is expected. Then have a new header for the metadata file section that goes over the metadata file information.

**Comment by karawoo** [comment]
We have some information about this under the "Data validation" header below. I think they just got swapped somehow.
