### ISSUE TITLE
CRAN status badge broken

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#302]
Noticed that the CRAN status badge is broken on the readme.

**Comment by karawoo** [comment]
Is it still broken for you? Looks ok to me now

![Screen Shot 2020-02-28 at 9 46 03 AM](https://user-images.githubusercontent.com/4452678/75571990-292c4d80-5a0f-11ea-9199-65d6a4d14141.png)

**Comment by Aryllen** [comment]
That's odd. It looks fine now, but it was broken last night. I'll close this issue.
