### ISSUE TITLE
Check that 'parent' in the manifest is a synID

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#318]
The `parent` column in the manifest is required to be complete. However, we had a contributor pass this check with simply putting "syn" in every row. We need to add a check that every value in the column is a synID. It might be beneficial to check that there is only a single unique value, as well, but that does limit the data to being uploaded to a single folder every time.

**Comment by karawoo** [comment]
> It might be beneficial to check that there is only a single unique value, as well, but that does limit the data to being uploaded to a single folder every time.

Often data gets uploaded to different folders, so I don't think we should enforce this.

**Comment by Aryllen** [comment]
> Often data gets uploaded to different folders, so I don't think we should enforce this.

Thank you for the information! Definitely shouldn't enforce a single parent folder, then.
