### ISSUE TITLE
Fix visibility of Travis builds

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#323]
Travis builds are not being shown in the GitHub PR anymore. Not a serious issue since these are still running and accessible in Travis, but would be nice to have them function nicely with GitHub, again. Need to either change to using the GitHub app for Travis or using GitHub Actions, instead.

**Comment by karawoo** [comment]
This might have been an issue with Travis that's been resolved https://www.traviscistatus.com/incidents/rx6fhs3wqcln

**Comment by Aryllen** [comment]
This does appear to be resolved. Yay!
