### ISSUE TITLE
Fix pkgdown deployment

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#327]
Deployment stage is failing due to some credential issue.

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Sage-Bionetworks/dccvalidator.git/'
```

https://travis-ci.org/github/Sage-Bionetworks/dccvalidator/builds/667406508

**Comment by Aryllen** [comment]
Ugh. I hope that's an easy fix, but I would not be surprised if that was related to using the "legacy" services version of Travis on GH.

**Comment by karawoo** [comment]
Still broken 😢

**Comment by Aryllen** [comment]
Shucks. 😢

**Comment by karawoo** [comment]
I'm running out of ideas :(

**Comment by Aryllen** [comment]
:( I'll try to look at this when I get a chance to see if I can come up with any other ideas.
