### ISSUE TITLE
Error missing value where TRUE/FALSE is needed

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#341]
Updated dccmonitor-test to use latest version of dccvalidator and it now has an error when trying to validate some of the files. Need to:
1. Make sure this is a dccvalidator problem, not a dccmonitor problem (it will validate some of the files).
2. Find where this is happening and fix it.

**Comment by karawoo** [comment]
It could be this line if sometimes the data has missing values for species? 

https://github.com/Sage-Bionetworks/dccvalidator/blob/1f7b7675dd401312e4842cb7bd62f4e260e28a61/R/check-all.R#L244

**Comment by Aryllen** [comment]
I'm thinking it might be that line, as well. I have the latest version on the [test app](https://shinypro.synapse.org/users/nkauer/dccmonitor-test/). It runs fine for the human study, but fails on the drosophila and mouse or other animal model studies. At the very least, it _should_ get `FALSE` for that check on the mouse or other animal model study.

**Comment by Aryllen** [comment]
Yup.
```
> species <- c(NA, NA, "mouse")
> any(species == "human")
[1] NA
```
That was my bad. I forgot that `any` doesn't work as expected for `FALSE` if there are `NA`s present. 
*insert facepalm gif here*
