### ISSUE TITLE
Add check for no duplicate paths in manifest

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#343]
Had a contributor who did not understand the manifest file and believed there should be one row per individual/specimen for each metadata file. Their files passed because it was filled out, but it was also incorrect.

All paths should be unique in the manifest. Adding this check would have at least given a notice to the contributor that something was wrong.

Granted, the file paths were also not real paths to files, but I'm not sure how to fix that problem, yet (one idea would be run syncToSynapse as a dryRun and see if that succeeds, but there's potential issues with that).

**Comment by karawoo** [comment]
> (one idea would be run syncToSynapse as a dryRun and see if that succeeds, but there's potential issues with that)

Unfortunately syncToSynapse dry runs don't check the validity of file paths. There's an open jira for that from yours truly: https://sagebionetworks.jira.com/browse/SYNPY-660. And since the app doesn't have access to the user's file system, it won't be able to check whether the files actually exist at the given location.

**Comment by Aryllen** [comment]
> Unfortunately syncToSynapse dry runs don't check the validity of file paths.

It wouldn't check for validity, which would then be another problem (we could add a check for that, as well). But it should check that the files are at the location specified. For example, the dryRun should fail if the path is "/path/to/metadata" because that's not a real path to anything.

> And since the app doesn't have access to the user's file system, it won't be able to check whether the files actually exist at the given location.

That's true. :( @kelshmo also mentioned that the user would probably run into a permissions error if they tried anyway since we don't give them access to upload until after they've validated.
