### ISSUE TITLE
Consider adding acknowledgement statement upload

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#344]
There is only a little blurb about adding an acknowledgement statement in the dccvalidator docs, and are generally asking for this in email. Should we add a separate upload for the acknowledgement statement? Would this be irrelevant for other consortia using the tool?

**Comment by karawoo** [comment]
If I'm not mistaken there's been talk of moving to a single acknowledgement statement, if so then this would become irrelevant.

**Comment by Aryllen** [comment]
Oh, that's true! I forgot about that. For groups that already use the single acknowledgement statement, it would already be irrelevant. Thank you for the reminder! I'm going to close this with `wontfix`.
