### ISSUE TITLE
check_ages_over_90 error when all NA

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#352]
`check_ages_over_90()` is breaking when the values in `ageDeath` are all `NA`. The error is that there is a missing value where true/false is needed.

It's probably this line: https://github.com/Sage-Bionetworks/dccvalidator/blob/dc3d97a94b9f7056b726fc69525380110f3531e3/R/check-ages-over-90.R#L39

**Comment by karawoo** [comment]
I should have added a test for that, sorry, I can fix

**Comment by Aryllen** [comment]
No worries, and thank you!

**Comment by karawoo** [comment]
reprex: 
``` r
library("dccvalidator")
#> Loading required package: shinyBS
dat <- data.frame(ageDeath = c(NA, NA))
check_ages_over_90(dat)
#> Error in if (!any(purrr::map_lgl(age_data, ~any(is_over_90(.x))))) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
