### ISSUE TITLE
Check_ages_over_90 error with decimal ages

### ISSUE THREAD

**Issue by bememea** [Sage-Bionetworks/dccvalidator#355]
I got warnings for ages over 90 in a human individual metadata file where ages had already been censored.  The file had ages as decimals, and every ageDeath was flagged:  once the decimals are taken out, ages appear to be bigger than they are (78.0 becomes 780).

``` r
is_over_90 <- function(x) {
  col_numeric <- gsub("[^0-9]", "", x)
  as.numeric(as.character(col_numeric)) > 90
}

is_over_90('78')
#> [1] FALSE
is_over_90('78.0')
#> [1] TRUE
```

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by karawoo** [comment]
Oh geez 🤦‍♀️  I will fix this ASAP. Thanks for reporting!
