### ISSUE TITLE
Clarify wording on different checks

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#376]
I will put a checklist of the different checks below, later. Should probably go through each one and try to clarify them as best as possible.

Based on feedback from Duminda.

**Comment by Aryllen** [comment]
I think I captured all of the messages for each check below. Some things I noticed while compiling:
- a check that was able to happen may have a clear message, but if the check was unable to happen (e.g. missing the column) then there can be overlap between other check messages
- if a check was unable to happen, we sometimes give warnings and sometimes give failures; may want to decide if these should all be similar (either warn or fail)

I included the behavior messages since we may want to clarify further or give more hints.

Suggestion for moving forward: quote and edit the following list.

These have the same messages regardless of metadata type. In the following list '---' stands for assay, individual, biospecimen/specimen, or manifest.

**check_cols**
Check that all template keys are present in the header
  - _success:_ All --- columns present
  - _fail:_ Missing columns in the --- metadata file
  - _behavior:_ --- file should contain columns: {list of columns}

**check_indiv/spec_ids_match**
Check that individual or specimen IDs are present across files
  - _success:_ All ---ID values match between --- and ---
  - _fail:_ ---ID values are mismatched between --- and ---
  - _behavior:_ ---ID values in the --- and --- metadata should match

Note: If missing individualID/specimenID column
  - _fail:_ Missing column ---ID in --- or --- metadata
  - _behavior:_ --- and --- metadata should both contain a column called ---ID

**check_annotation_keys**
Check that annotation keys in the manifest are accepted annotation keys (i.e. there should be no extra, unaccepted keys)
  - _success:_ All keys (column names) in the manifest are valid
  - _fail:_ Some keys (column names) in the manifest are invalid
  - _behavior:_ All annotation keys should conform to the vocabulary. Refer to the annotation dictionary for accepted values.

**check_annotation_values**
Check that the values in the metadata are dictionary compliant based on key
  - _success:_ All values in the --- are valid
  - _fail:_ Some values in the --- are invalid
  - _behavior:_ All annotation values should conform to the vocabulary. Refer to the annotation dictionary for accepted values.

**check_indiv/spec_ids_dup**
Check that individual/specimen IDs are unique in their respective files
  - _success:_ --- IDs in the --- metadata file are unique
  - _fail:_ Duplicate --- IDs found in the --- metadata file
  - _behavior:_ --- IDs within the --- metadata should be unique

If no individualID/specimenID column:
  - _fail:_ Can't check for duplicate --- IDs: ---ID column missing from data
  - _behavior:_ --- metadata should contain ---ID column

**check_cols_empty**
Check if any columns (required or not) were left completely blank
  - _success:_ No columns are empty in the ---
  - _fail:_ Some columns are empty in the ---
  - _behavior:_ Completely empty columns might be an accidental omission. If the columns are empty because the data does not exist, then this check can be ignored.

**check_cols_complete**
Check that required columns are complete
  - _success:_ All required columns present are complete in the --- metadata
  - _fail:_ Some required columns are incomplete in the --- metadata
  - _behavior:_ Columns {list of required columns} should be complete.

**check_files_manifest**
Check that metadata files are present in the manifest
  - _success:_ Manifest file contains all metadata files
  - _fail:_ Manifest file does not contain all metadata files
  - _behavior:_ The following files should be present in the manifest: {names_collapsed}. However, if this is an update to an existing study and the files have not changed since they were last released, this warning can be ignored.

If missing path column:
  - _fail:_ Manifest is missing `path` column
  - _behavior:_ Manifest should contain a column called `path`

**check_parent_syn**
Check that the synIDs in the parent column are valid
  - _success:_ All Synapse IDs in the manifest are valid
  - _fail:_ Some Synapse IDs in the manifest are invalid
  - _behavior:_ Synapse IDs should follow the format 'syn' followed by digits

If no parent column present:
  - _fail:_ Manifest is missing `parent` column
  - _behavior:_ Manifest should contain a column called `parent`

**check_duplicate_paths**
Check that there all paths in the manifest are unique
  - _success:_ No duplicate file paths detected
  - _fail:_ Duplicate file paths detected
  - _behavior:_ File paths in the manifest should be unique; you cannot upload duplicate files.

If no path column in manifest:
  - _warn:_ Could not check for duplicate file paths because data does not contain `path` column
  - _behavior:_ File paths in the manifest should be unique; you cannot upload duplicate files.

If path column is empty:
  - _warn:_ Could not check for duplicate file paths because all file paths are missing
  - _behavior:_ File paths in the manifest should be unique; you cannot upload duplicate files.

**check_ages_over_90**
Check if there are uncensored ages over 90
  - _success:_ No ages over 90 detected in the --- metadata
  - _fail:_ Ages over 90 detected in the --- metadata
  - _behavior:_ Ages over 90 should be censored and written as '90+'.

**check_complete_ids**
Check that existing studies have included prior metadata in their new metadata file
  - _success:_ All pre-existing --- IDs are present in the --- file
  - _fail:_ Some --- IDs that were previously part of this study are missing from the --- file
  - _behavior:_ If the data being validated is an addition to an existing study, all IDs that were previously shared for this study should be included in the metadata

If missing ---ID column
  -_fail:_ Can't check for complete IDs because ---ID column is missing from data
  -_behavior:_ If the data being validated is an addition to an existing study, all IDs that were previously shared for this study should be included in the metadata

**Comment by Aryllen** [comment]
Also, if it would be easier to see/compare these, I would be willing to copy/paste these into a spreadsheet with the following header:

check_type | reason for being unable to check (if applicable) | success | fail/warn | behavior

**Comment by karawoo** [comment]
`check_cols`/`check_cols_complete`/`check_cols_empty` seem to be the biggest source of confusion
`check_cols` vs `check_annotation_keys` for the manifest also may be confusing

**Comment by Aryllen** [comment]
Suggested ideas for updating behavior on two of these checks.

> **check_cols**
> _behavior:_ --- file should contain keys (column names): {list of columns}. If you do not have data related to a key, the key should be present and the column should be empty.

> **check_cols_complete**
> _behavior:_ There should be no missing values in columns {list of required columns}.
