### ISSUE TITLE
Add next step prompt after no failures

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#378]
Add a prompt to contact the curation team for the next step, if all files were validated together and there are no failures. This would help the users know what to do next.

One challenge with this is that they can validate any number of files together. It would be annoying to get the prompt after every validation if they are validating them by themselves first. However, not all groups will have 3+ files so adding logic to only have this pop up with this criteria would also be a challenge.

Based on feedback from Duminda.

**Comment by karawoo** [comment]
Since we don't have a way to know how many files they should be validating, I'd be inclined to show the message anytime there are no failures, and just try to make the message not too annoying or intrusive. How does that sound to you @Aryllen?

**Comment by karawoo** [comment]
Need to make it clear that a) they're only done if they've validated all their files together, b) they need to contact us before uploading
