### ISSUE TITLE
Error converted from warning

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#38]
When executing:
`devtools::install_github("Sage-Bionetworks/dccvalidator")`

Returned this error message reproduced in two distinct environments: 

```
Error: (converted from warning) unable to access index for repository /src/contrib:
  cannot open URL '/src/contrib/PACKAGES'
```

**Comment by karawoo** [comment]
Sorry I didn't see this until now. I can't reproduce, can you provide the output of `sessionInfo()`? I'm guessing you've run into this [remotes bug](https://github.com/r-lib/remotes/issues/251) and updating the remotes package will fix it.

A workaround to the error is: `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")`

**Comment by kelshmo** [comment]
Updating to R version 3.6.0 and re-installing `synapser`, `PythonEmbedInR` and `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")` resolved the problem.
