### ISSUE TITLE
New CRAN Release Required

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#387]
See message below. It looks like shinyjs and jsonvalidate both use V8 (although jsonvalidate is only a suggests for us). Since neither are on the list, I assume they have updates that remove this dependency. Should update the packages to the latest versions (and require these versions).

> Package V8 no longer installs on fedora-clang after upgrading to Fedora 32.
> 
> Packages
> 
> codemetar datarobot dccvalidator dm dqshiny ggforce mcmcabn shinyMobile
> sparrpowR textplot
> 
> suggest it or a package which requires it but do not use it
> conditionally (see §1.1.3.1 of 'Writing R Extensions').
> 
> Please correct ASAP and before June 30 to safely retain the package on CRAN.

**Comment by Aryllen** [comment]
@karawoo, I was wrong, there are not newer versions of those packages that remove V8. jsonvalidate is already a "suggests". The 'Writing R Extensions' documentation is a bit dense, but from my interpretation of the docs and the email, it appears that we cannot have any packages that use V8 in "depends" or "imports". Am I correct in thinking that it would be adequate to move any packages that need V8 to "suggests" instead of "imports"?

**Comment by karawoo** [comment]
I think we just have to make sure that R CMD check passes if these dependencies aren't installed. You can see the errors in our tests that use jsonvalidate here: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/dccvalidator-00check.html (note for future reference that these will change daily so here's a screenshot from today)
![Screen Shot 2020-06-16 at 10 02 08 AM](https://user-images.githubusercontent.com/4452678/84805063-86491080-afb8-11ea-9e93-703263da60c0.png)

I think it should be enough to add `skip_on_cran()` or `skip_if_not(requireNamespace("jsonvalidate", quietly = TRUE))` to the tests in `test-check-schema-json.R` and `test-check-schema-df.R`.

**Comment by Aryllen** [comment]
Oh, I see what you mean. Thanks, @karawoo!
