### ISSUE TITLE
Add fileview query after upload

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#431]
Fileviews only update after being queried. Add a small query to the fileviews needed for dccmonitor after every upload set to keep them in sync. This may mean adding `consortium_fileview` from the [dccmonitor config](https://github.com/Sage-Bionetworks/dccmonitor/blob/master/config.yml) to the dccvalidator config. If someone is building tools off these fileviews, they need to stay up to date.

**Comment by karawoo** [comment]
I think this is a duplicate of #361

**Comment by Aryllen** [comment]
Bah, I even tried searching for it because I could swear I made this issue already. 😆 Will close this one and mark the other one as high priority since this is a relatively simple update and there is already at least one tool that assumes the table is up to date.
