### ISSUE TITLE
Suppress expected warning message output on test

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#436]
We are now getting a warning message when we run this test. The error is expected and desired, the message is not.

https://github.com/Sage-Bionetworks/dccvalidator/blob/6a0a0a143473baebd8f7c4af6beea4bfca97768c/tests/testthat/test-check-col-names.R#L26-L31

**Comment by mattfazza** [comment]
I was able to reproduce the error.  It's not clear to me what the type of the message in the console is.  Solutions such as 
```r
options(warn=-1)
```
```r
suppressMessages()
```
```r
suppressWarnings()
```
```r
invisible()
```
```r
sink()
```
didn't work for me.  I had trouble stepping through with the debugger on my Rstudio for this test file, but I'm not sure these are being surfaced in the standard output/error as warnings or messages.  Any thoughts?

**Comment by karawoo** [comment]
That warning message is coming from Python so I think we need `reticulate::py_suppress_warnings()`

**Comment by Aryllen** [comment]
Thanks for checking this out, @mattfazza!

I agree with Kara. Hopefully having reticulate suppress the python warning will make it stop. I don't think I have tried that, yet.

**Comment by mattfazza** [comment]
Ok, I just tested it out real quick, and `reticulate::py_suppress_warnings()` is not working.   It's as if this is not being treated as a warnings, but I checked stderr, and the output is there.  `reticulate::py_capture_output()` from stderr seems to be working fine.  I'll branch out/make a PR soon.  Thanks for the nod in the right direction @karawoo !
