### ISSUE TITLE
Make documentation and instruction pages optional

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#460]
Documentation upload is moving elsewhere for AD and PEC. I'd like to try making a new config setting that would only generate the documentation and instruction pages if the set to TRUE.

**Comment by kelshmo** [comment]
I like a config option for building the documentation page. Would that obscure the entire tab? 

Could we develop an interim solution that removes the left panel (with the upload widget) but preserves the documentation tab and free text? For posterity, we could add text that redirects to the submission form, as some users might expect to upload documentation in that tab.

**Comment by Aryllen** [comment]
> Would that obscure the entire tab?

That was my idea. If the application wasn't used for uploading documentation, then the tab isn't needed.

> Could we develop an interim solution that removes the left panel (with the upload widget) but preserves the documentation tab and free text? For posterity, we could add text that redirects to the submission form, as some users might expect to upload documentation in that tab.

That's an interesting idea. I was thinking of removing the tab altogether, especially since there's always a challenge with keeping multiple sources of information in sync. It might be neat to make both the tab and the upload section optional. That would give someone the ability to have the tab with free text, the tab with free text and the ability to upload, or no tab at all. No idea how reasonable of a change that is, but worth a try!

**Comment by kelshmo** [comment]
This came up in a discussion with Juliane and Mette - their preference would be to link to the Synapes form from this tab, at least in the interim, since instructions to visit the Documentation tab have already been distributed to some.

**Comment by kelshmo** [comment]
What is your prioritization of new features in dccvalidator?

**Comment by Aryllen** [comment]
That's a good question and one that has been in the back of my mind for a while now. I'm hoping to give it more thought this week, but if there are features or issues that you would like to see sooner rather than later, please let me know. Feel free to comment on the issue itself or send me a list of issues in Slack or email.

**Comment by kelshmo** [comment]
This could be considered a high priority issue as the submission form is configured and ready to go!

**Comment by Aryllen** [comment]
Thanks for the update. I'm experimenting with having a project where I can put issues in a queue, of sorts. I'll add this to it. My first focus is going to be taking care of all the PRs in here (many need updates before merging). After that, I'll try working on both this and json schema support.
