### ISSUE TITLE
Update AD instructions to point to docs submission form

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#462]
The vignette for the AD instructions is [here](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/inst/using-the-dccvalidator-app-amp-ad.Rmd). This needs to be updated to remove information about uploading via the documentation tab and, instead, pointing the user to the Synapse submission form [here](https://www.synapse.org/#!Synapse:syn25051271).

@avanlinden and @pitviper6, due to this being an instruction set, I want to make sure it's correct for how you would like people to submit/validate data. I am a little out of the loop on the AD process other than knowing that docs are going to the submission form. Would you be able to give me the information you want in these two sections below? Alternatively, @avanlinden, this is an Rmarkdown file. If you would feel comfortable enough, feel free to start a branch with PR to update with changes.

https://github.com/Sage-Bionetworks/dccvalidator/blob/b122c93a796d613cb6846fa908a1625d72f5fd9c/inst/using-the-dccvalidator-app-amp-ad.Rmd#L47-L67

**Comment by avanlinden** [comment]
[PR here](https://github.com/Sage-Bionetworks/dccvalidator/pull/464). 

Nicole, any idea why the changes failed so many checks? Looks like maybe a credentials issue and some dependency issues?

**Comment by Aryllen** [comment]
@avanlinden, it is due to being a fork and not having the credentials needed to access Synapse. Although it is confusing that the Windows version passed. 😕

**Comment by avanlinden** [comment]
Ok that's what I thought but the Windows pass threw me off! Weird.
