### ISSUE TITLE
Update PEC instructions to point to docs submission form

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#463]
@kelshmo, now that PEC is using the docs submission form in Synapse, the instructions page should be updated to reflect this. Would you please either create a branch and update the docs or let me know in this issue what the change(s)/wording should be? After a brief scan, it looks like this section below is the only one that needs updated.

https://github.com/Sage-Bionetworks/dccvalidator/blob/b122c93a796d613cb6846fa908a1625d72f5fd9c/inst/using-the-dccvalidator-pec.Rmd#L65-L70

**Comment by kelshmo** [comment]
Can we change the instructions page after the documentation tab is removed from the app?

**Comment by Aryllen** [comment]
> Rather the widget to upload documentation in the app will be removed. Is that possible now?

This has not been my intention. Removing the widget, while possible right now, would remove it for everyone.

There could be a double layer customization (I think) where someone could have a documentation tab with a widget or a documentation tab without a widget or no documentation tab at all. That will take more work, though.

**Comment by Aryllen** [comment]
Closing since this is done.
