### ISSUE TITLE
Add biospecimen type config options for PEC and VEOIBD

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/dccvalidator#499]
@kelshmo, do you want to use the new biospecimen type feature? If so, I will need to know what you want your biospecimen types to be called and which templates they refer to, respectively. Please do not update dccvalidator until the config is updated.

@amapeters, same question as above for VEOIBD.

**Comment by kelshmo** [comment]
Fixed for PEC in #505.
