### ISSUE TITLE
Tibble error after reset

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#508]
To reproduce the error: 

```
Error: Tibble columns must have compatible sizes. * Size 4: Existing data. * Size 3: Column `template`. ℹ Only values of size one are recycled.
```

Upload some metadata files and click **validate**.  Then, select **reset**. Browse and upload the same metadata files (without refreshing the page). Then, click **validate** again. I triggered the error by testing biospecimen and assay files only.

**Comment by Aryllen** [comment]
Bah. Thank you for catching and reporting. Will get to this as soon as I can (probably after the break). Hopefully no one is using the reset button in the next week...
