### ISSUE TITLE
Investigate using JSONSchemas instead of xlsx templates

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/dccvalidator#527]
The xlsx templates that dccvalidator and dccmonitor use to validate datasets can become out of date if their JSONSchemas are updated. Using the JSONSchema directly would eliminate the need to keep these spreadsheets up to date.

**Comment by avanlinden** [comment]
@afwillia the xlsx templates will still need to be kept up to date, because our contributors use those to supply their metadata for validation. But having the JSON schemas be the source of truth for dccvalidator/monitor, and then generating an updated xlsx template based on changes to the schemas for contributor use, would definitely be an improvement. 

Ideally changes to a JSON schema would trigger a workflow to run the script that updates the xlsx template files and stores the newest versions to synapse--we have an issue open for this [here](https://github.com/Sage-Bionetworks/sysbioDCCjsonschemas/issues/116), and I think Dan is working on it, but I don't know how far she's gotten.

**Comment by afwillia** [comment]
Linking issue #528 here

**Comment by afwillia** [comment]
After some investigation, it looks like the apps are already able to use registered schemas for checking column names of the assay data, woo! But there are two checks against the annotation table that use the synapse xlsx. These functions lack the ability to look up the AMP AD schema, but it could be done.

Also, after discussions with @milen-sage, it would be possible to keep the xlsx templates and registered JSON schemas in sync by using a data model csv with schematic.

**Comment by afwillia** [comment]
I was under the impression that the [AMP AD Metadata table ](https://www.synapse.org/#!Synapse:syn21459391/tables/) was generated by the [AD schema](https://github.com/Sage-Bionetworks/sysbioDCCjsonschemas/blob/master/schema_annotations/AD/ad_schema.json), but I'm not sure that's correct since the metadata table is not an xlsx. @avanlinden can you clarify how those two datasets are related?

**Comment by avanlinden** [comment]
@afwillia The AD metadata dictionary table in Synapse is generated by [this python script](https://github.com/Sage-Bionetworks/sysbioDCCjsonschemas/blob/master/code/python/create_Syn_table_from_Syn_schemas.py), which uses the [JSON schema files for each template](https://github.com/Sage-Bionetworks/sysbioDCCjsonschemas/tree/master/schema_metadata_templates) and a config file stored in the sysbioDCCjsonschemas repo to de-reference all the AD-specific dictionary terms registered in Synapse and build/update the dictionary table.

That AD Schema file you linked is meant to be used as the annotation schema bound to the AD portal Synapse project, when schematized annotations in Synapse are live. That file is not used for anything yet.

**Comment by ychae** [comment]
- [ ] how much work will it take to have the same backend for validation scheme?
Acceptance Criteria:
1. Decide what work it would take to generate data model csvs that can fully replicate SysBio's current templates
2. Replicate validation checks

**Comment by avanlinden** [comment]
@afwillia The [excel test templates](https://www.synapse.org/#!Synapse:syn26989883/files/) you generated are fantastic! I think this is going to help our data contributors a lot. I have a couple of notes and questions, in no particular order:

1. I know it's a feature of the schematic data model, but can we remove the "component" column from the excel template or hide it somehow?
2. The drop-down menus are going to be game changers. Is there a way we can have the drop-down options appear in alphabetical order?
3. Just confirming that the keys listed as required in the schemas appear as the blue columns -- this makes sense to me
4. The boolean columns like isModelSystem/isMultiSpecimen need to be constrained to either TRUE or FALSE, but there's no drop-down or controlled values on these columns.
