### ISSUE TITLE
Sysbio template_assay_RNAseq.xlsx is out of date

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/dccvalidator#528]
It appears the [xlsx template](https://www.synapse.org/#!Synapse:syn12973256) for [sysbio.metadataTemplates-assay.rnaSeq](https://github.com/Sage-Bionetworks/sysbioDCCjsonschemas/blob/master/schema_metadata_templates/shared/assay_rnaSeq_metadata_template.json) is out of date.

To verify this, run dccvalidator configured with `AMP AD``assay_templates` `rnaSeq:sysbio.metadataTemplates-assay.rnaSeq`
and then again using `rnaSeq:syn12973256`

Use the t[hree APOEPSC files here](https://www.synapse.org/#!Synapse:syn26720291) to validate. The schema config run should generate an error for missing columns in the assay data. The synapse table run will not.

**Comment by avanlinden** [comment]
Wild, this has been mismatched since at least July based on the commit history and we didn't realize it.

I'll regenerate the excel template from the schema and upload the new version to Synapse as a stop-gap. Obviously a good example of the bigger desynchronization problems we have though!

**Comment by avanlinden** [comment]
Regenerated the excel template file and added it to the template folder. Validation should be ok now.

**Comment by afwillia** [comment]
Just confirmed that dccvalidator checks are now the same between the schema and updated xlsx file. Thanks!
