### ISSUE TITLE
Allow dccvalidator to read vanilla JSONSchema

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/dccvalidator#529]
Currently, the dccvalidator uses JSONSchema registered in Synapse. To allow flexibility of input types, we can add support for reading JSONSchema 

- [x] from a local file
- [x] at a given url

How important is this feature? 
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

When will use cases depending on this become relevant? Select from the options below:
• Long-term - 6 months - 1 year

Additional context
Other necessary refactors discovered will be defined in the future.

**Comment by milen-sage** [comment]
Acceptance criteria - pass a file path or url to config file instead of a synapse table or schema name, and have the app run as usual.

**Comment by afwillia** [comment]
@ychae just an update, I haven't made progress on this, but am planning to address next week.

**Comment by afwillia** [comment]
@ychae added in https://github.com/Sage-Bionetworks/dccvalidator/pull/531
