### ISSUE TITLE
Update Administrator for PEC dccvalidator 

### ISSUE THREAD

**Issue by danlu1** [Sage-Bionetworks/dccvalidator#530]
Kelsey is still the administrator for PEC dccvalidator (https://www.synapse.org/#!Synapse:syn21763123). Do you know how can I replace her with [PEC_SageAdmin](https://www.synapse.org/#!Team:3328037) as admin? @afwillia

**Comment by afwillia** [comment]
@danlu1 My guess is that Kelsey needs to change the "Folder Sharing Settings" under "Folder Tools". If that doesn't work then maybe IT can help.

**Comment by danlu1** [comment]
Gotcha! Kelsey has already left Sage and I will submit a ticket to Jira. Thanks a lot!

**Comment by danlu1** [comment]
Update: I've emailed Kelsey to update this.

**Comment by danlu1** [comment]
Done updating.
