### ISSUE TITLE
Update SysBio data model csv

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/dccvalidator#532]
Address [Abby's comments](https://github.com/Sage-Bionetworks/dccvalidator/issues/527#issuecomment-1039458267) about the metadata templates.

**Comment by afwillia** [comment]
@avanlinden I updated the data model to require TRUE/FALSE for any fields that start with "is" or with "boolean" in the description. Also, I removed the `Component` column from the templates. The alphabetized dropdown menu will be implemented in schematic, so I'll update these again soon.

I pushed all of the updated data objects to a [fork](https://github.com/afwillia/sysbioDCCjsonschemas/tree/schematic_workflow/schema_metadata_templates/schematic_test). We should discuss how to organize and store these in the actual repo. Any thoughts? Also, the updated xlsx templates are on [my test synapse page](https://www.synapse.org/#!Synapse:syn26989883/files/).

**Comment by avanlinden** [comment]
@afwillia This looks great!

Would it make sense to have the results of the schematic workflow in their own top-level folder in the repo?

**Comment by afwillia** [comment]
@avanlinden that sounds good to me. It's a handful of files and directories to keep track of, but ideally only one file gets edited by hand. The key here will be documenting the workflow and making it as hands-off as possible. For hindsight, here are steps I've taken just to make this change.

1. Update `amp.ad.data.model.csv` data model by hand.
2. Convert data model to json schema using schematic and a [minimal model](https://github.com/imCORE-DCC/data_model/blob/production/minimal.model.jsonld) `schematic schema convert --base_schema ./minimal.model.jsonld ./amp.ad.data.model.csv` with [create_schemas.sh](https://github.com/afwillia/sysbioDCCjsonschemas/blob/schematic_workflow/code/schematic_workflow/create_schemas.sh)
3. Create a google sheet template and json for each data type `schematic manifest --config config.yml get -s -oa -p ./amp.ad.data.model.jsonld -t IndividualHumanMetadataTemplate -dt IndividualHumanMetadataTemplate`
4. Manually download all the google sheets as xlsx. Using the google drive API would be clutch.
5. Upload all the xlsx templates to [synapse](https://www.synapse.org/#!Synapse:syn26989883/files/)
6. Register the json schemas to synapse by tinkering with [register-schemas.py](https://github.com/afwillia/sysbioDCCjsonschemas/blob/schematic_workflow/code/schematic_workflow/register-schemas.py) for each schema.
7. Commit the data model, model jsonld, json schemas, xlsx templates and push to repo.

**Comment by afwillia** [comment]
@ychae addressed in [PR134](https://github.com/Sage-Bionetworks/sysbioDCCjsonschemas/pull/134)
