### ISSUE TITLE
Investigate how .synapseSession file is used

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/dccvalidator#537]
There is a bug where a user uploads files as the host of the shiny app. Removing .synapseSession resolved this, but it's unclear how.

**Comment by avanlinden** [comment]
There doesn't appear to be any documentation that I can find on the .synapseSession file, but Tom's hypothesis was that it's where the username is stored if you login with `--rememberMe=true`.

**Comment by afwillia** [comment]
That sounds like a good idea. It could happen on Shiny Server if I used the synapse CLI. I see that dccvalidator::attempt_login() tries to log in without arguments first, even if the user has obtained an auth token. I'll put together a minimal example of this. Then someone can try logging in and seeing if it uses their token or mine.

**Comment by afwillia** [comment]
Tom was correct - when you log in with `rememberMe = TRUE`, the password is stored in the keyring and the username is stored in .synapseSession. If no credentials are provided to the login command, it searches for them in several places (.synapseConfig, .synapseSession, some AWS thing). `dccvalidator::attempt_login()` first tries the synapse client login with no arguments, even if an auth token is provided. This means if .synapseSession or .synapseConfig are present, those credentials will be used by the app.

In this instance, running the synapse python CLI on Shiny Server with `rememberMe=TRUE` at some point created  .synapseSession, so even though users went through the OAuth process, they were ultimately logged in as the shiny app owner.
