### ISSUE TITLE
Support validating additions to existing datasets

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#55]
Sometimes we get new data/metadata for an existing study. The validation app doesn't know about the existing data, so it might report erroneous mismatches between the metadata and manifest (for example, if the metadata contains specimens that are not in the manifest, but correspond to existing data). Need to think through how to support this. One possibility is sketched out below:

![IMG_9783](https://user-images.githubusercontent.com/4452678/60553185-07938e80-9ce7-11e9-9978-8c0416af1853.JPG)

**Comment by kelshmo** [comment]
If PEC contributors use Synapse as planned, we would frequently have users add to their existing, growing dataset instead of waiting and uploading everything in bulk.

**Comment by karawoo** [comment]
Maybe a first step should be to allow whitelisting specific IDs rather than creating a file view of all the data.

**Comment by karawoo** [comment]
Our approach for this should also work for new studies that have multiple assays but a single biospecimen and individual file.

**Comment by karawoo** [comment]
> Maybe a first step should be to allow whitelisting specific IDs rather than creating a file view of all the data.

To provide more info on what I'm thinking here: we could have a question like "is this part of a larger study (e.g. with multiple assays, or prior uploaded data)?" -- if yes, provide two input boxes that will allow the user to provide individual IDs and specimen IDs to whitelist. This should be optional, but there should be some explanation that if they don't provide them, they might see spurious errors.

**Comment by Aryllen** [comment]
@karawoo and I discussed this issue in person. We figured that the easiest way of fixing the issue of existing datasets is to use the AMP-AD All Studies file view to get the specimenIds and whitelist those ids. If we just allow the user to choose the ids to whitelist, it would be frustrating for the user and there could still be errors. This mitigates this problem. This does not address the comment above about new studies with multiple assays, but issue #80 addresses this problem.

**Comment by amapeters** [comment]
What about the following scenario

We have an existing specimen and/or individual metadata file, but the data is a multi specimen matrix only, ie, no individualID or specimenID in the file view because of the multiple annotations issue.

**Comment by karawoo** [comment]
Aargh I forgot about that. Yes @Aryllen we didn't consider this case -- some data files won't be annotated with their specimenIDs because of the multiple annotation issue I mentioned. So with the file view approach, we might not have a complete list of specimen IDs...

@amapeters part of our concern with the option of whitelisting IDs is that it doesn't save us from then having to check the IDs ourselves manually. It would be very easy to whitelist IDs other than those in the existing data, so the curators would still need to perform this check later on.

**Comment by karawoo** [comment]
@amapeters Do we have a list of _all_ specimen and individual IDs from existing studies (not just the ones in annotations) somewhere? In one of the tables Yooree built for the portal, maybe?

**Comment by amapeters** [comment]
We do for human data. It was generated in order to have a list of individual IDs to generate figures from. It's here: https://www.synapse.org/#!Synapse:syn20165259/tables/

I had considered that table temporary, but let's make sure we maintain it and add the model info

**Comment by amapeters** [comment]
Wrong link. See here: syn18912660

**Comment by karawoo** [comment]
Ok that's good to know. I think we need to weigh whether creating the equivalent for models and maintaining this whole thing moving forward is worth the significant effort it would take. I think we should discuss this with the wider group.

**Comment by karawoo** [comment]
Agreed that updating the table and using that is the best approach.

**Comment by kelshmo** [comment]
I need some clarify on this approach to be able to implement it in PEC.

**Comment by karawoo** [comment]
Marking this as blocked because we do not have the table of individuals/specimens from model studies. @kelshmo let's talk more in our next meeting about how we could use this for PEC (or alternatives if it's not a good fit).

**Comment by karawoo** [comment]
Discussion with @amapeters and @bememea today: would it be feasible instead to have people upload the existing individual/biospecimen metadata file to the validator? If it hasn't changed, they can re-upload as-is, or we could ask them for the synID and look it up that way. If the metadata files have changed, e.g. due to new samples being collected, they should be validating it anyway. If there isn't an existing metadata file, then we will ask them to create one (as we are already planning to do).

We have already made changes to the app so that if the manifest describes a subset of the individuals/specimens in the metadata files, the validator will not complain. This change + re-using the existing metadata files seems a more maintainable approach than trying to keep a master table up to date.

**Comment by kelshmo** [comment]
Is the proposed change, to address the case of metadata that has not changed, to take a synID and validate that file?

**Comment by karawoo** [comment]
Yes, to take the synID and validate that file, or alternatively to have people download the existing file and re-upload it to the validator.

> I'm imaging the "metadata that has not changed" use case generally applies to cases where one wants to validate new assay metadata against existing biospecimen/individual data.

Yes, I think this is correct.

**Comment by karawoo** [comment]
Summarizing conversation from today: 

We do still need the table and it should have individualID, specimenID, study, _and_ assay. This is because we need to ensure that any new/updated _metadata_ files have the full list of specimens/individuals (i.e. to ensure they are not uploading just the few rows of metadata that corresponds to the new data they are uploading). So we will check the existing specimens for the given assay and ensure that any metadata files they upload has at least the same specimens (and possibly more).

We will also not expect to have this table in place before the November data release.

**Comment by karawoo** [comment]
I'm going to get started on this soon. @Aryllen, @kelshmo I am thinking about this approach and would love your feedback on the following: 

* We have 3 functions, `check_existing_ids_individual()`, `check_existing_ids_biospecimen()`, `check_existing_ids_assay()` that compare the IDs in the uploaded metadata files to the existing IDs in the master table
* Checking individual IDs should be pretty straightforward -- we check the individual metadata file against all individual IDs for that study.
* Checking specimen IDs is a little different. For the biospecimen file, I think we would check against all the specimen IDs. For the assay file, we would check against only the specimen IDs for that assay.
* In all cases, if the user uploads data that has new IDs, that's fine. If, however, they are _missing_ IDs that are preexisting in the master table, they will get a `"check_fail"`.
* One question is whether we have to check the individual IDs in _both_ the individual and the biospecimen metadata file against existing individual IDs? I don't think this is necessary but I keep getting myself slightly confused thinking about it.

**Comment by Aryllen** [comment]
> One question is whether we have to check the individual IDs in both the individual and the biospecimen metadata file against existing individual IDs? I don't think this is necessary but I keep getting myself slightly confused thinking about it.

This is a challenge. In general, it would seem weird to have an individual in the individual metadata, but not have them in the biospecimen metadata. Why include the person if no samples were taken or analyzed? However, I feel like there _might_ be a case I am not thinking of where it would make sense to not have them in the biospecimen metadata. For example, behaviorial or clinical data is not going to need to include biospecimen information because it is not done on a specimen, but the individual. Overall, I do agree that the biospecimen metadata should be checked for existing specimenIDs. I am wondering if we should be checking the individualIDs, but am struggling on what that check should be. Would it be that all individualIDs previously associated with a specimenID are in the template? Should we also be checking that these same individualIDs are associated with the same specimenIDs (i.e. if an individual was previously associated with specimenID spec1, then that individual should still be in the metadata as associated with spec1; if the new metadata did not have that individual associated with spec1 at all, but rather had them associated with spec2, then that would be a failure)?

> We have 3 functions, check_existing_ids_individual(), check_existing_ids_biospecimen(), check_existing_ids_assay() that compare the IDs in the uploaded metadata files to the existing IDs in the master table

I am wondering if we could have a single function that has a flag for the ID type versus three separate functions. Both the individual and assay metadata files would have the same functionality, but just be looking at a different column in the table. Just checking the specimenIDs in the biospecimen file is also the same functionality. The only difference is if we were checking something else as mentioned above. That could be a separate function, outside of just checking that the specimenIDs are all present, however; something like `check_existing_biospecimen_ids_match`.

**Comment by karawoo** [comment]
> In general, it would seem weird to have an individual in the individual metadata, but not have them in the biospecimen metadata.

We currently allow individual IDs to be in present in the individual file but absent from the biospecimen file through the use of `bidirectional = FALSE`. I think this is to deal with the case where there is behavioral and specimen-based data in the same study, as you mention, since the behavioral data will not have specimen IDs.

> Would it be that all individualIDs previously associated with a specimenID are in the template? Should we also be checking that these same individualIDs are associated with the same specimenIDs

I guess that is right. I don't know if we'd want to check that the specimen IDs are associated with the same individual. Sometimes after data is QCed there are updates where this changes intentionally (they realized samples got swapped, for example). 

If this is this confusing for us then I think the results of the check will be even more confusing to the user. I propose that for the biospecimen file, we just check against the existing specimen IDs for now.

**Comment by Aryllen** [comment]
> Sometimes after data is QCed there are updates where this changes intentionally (they realized samples got swapped, for example).

I feel like this would be an important to case to make note of if it happens. If we are unaware that this data is changing, we cannot make anyone else aware who may already be using it. Even a warning would be nice to notify us/them so that it can be verified whether this was intentional or not.

> I propose that for the biospecimen file, we just check against the existing specimen IDs for now.

I agree. I do think we may want to revisit the other issue in the future, though.

**Comment by kelshmo** [comment]
> Checking individual IDs should be pretty straightforward -- we check the individual metadata file against all individual IDs for that study.

Can we configure this to be able to check within study and across studies?

> In all cases, if the user uploads data that has new IDs, that's fine. If, however, they are missing IDs that are preexisting in the master table, they will get a "check_fail".

Can you clarify this case, @karawoo? In what case would a contributor trigger a fail for missing IDs?

> One question is whether we have to check the individual IDs in both the individual and the biospecimen metadata file against existing individual IDs? I don't think this is necessary but I keep getting myself slightly confused thinking about it.

In PEC, contributors will knowingly contribute data from the same individual across studies. It is likely clinical metadata on the individual already exists and I have been trying to figure out what action they should take to contribute data - e.g. validate with an individual file listing individuals but no other metadata, or skip validating the individual file all together? In the latter case, it would be helpful to get a warning from the biospecimen file if the individual does not exist. I'm all for a simple solution that solves the _most_ cases and am fine to punt on this request if it creates too much branching logic. 

> Would it be that all individualIDs previously associated with a specimenID are in the template? Should we also be checking that these same individualIDs are associated with the same specimenIDs

> I guess that is right. I don't know if we'd want to check that the specimen IDs are associated with the same individual. Sometimes after data is QCed there are updates where this changes intentionally (they realized samples got swapped, for example).

Also, a contributor might be intentionally contributing a second biospecimen and it would not make sense to give a warning for that case. I advocate for checking whether IDs exist and not how they map, for now. Perhaps we can track in another issue.

Hopefully, I didn't muddy the waters further... thank you Kara and Nicole.

**Comment by karawoo** [comment]
> Can we configure this to be able to check within study and across studies?

It seems to me that these two are basically opposite checks. In this issue, we want to ensure that contributors are providing complete metadata for their study. This means they should provide the existing metadata, plus any new individuals/specimens (as opposed to providing only the new information). We _want_ to find pre-existing IDs that match those in the files the contributor uploads. The check across studies is #257 and is the opposite. There, we would want to make sure they are _not_ duplicating IDs from other studies. I think these should be two separate checks.

It's possible @kelshmo that you have a use case for #257 but not for this issue. If that's the case, then I think we will need to start thinking about ways to configure which checks are run in `check_all()`. Until now, we have managed to avoid dealing with that as all the checks are the same across PEC and AMP.

**Comment by karawoo** [comment]
Sorry, I wrote this and then realized I was misinterpreting the PEC situation. So, to clarify: @kelshmo for this issue, do you want to make sure that the contributor has provided a metadata file that includes all the IDs across all studies in PEC?

**Comment by Aryllen** [comment]
> Also, a contributor might be intentionally contributing a second biospecimen and it would not make sense to give a warning for that case. I advocate for checking whether IDs exist and not how they map, for now. Perhaps we can track in another issue.

@kelshmo, my thought is that they would still be able to contribute a **new** biospecimen for an individual, but all **old** biospecimens associated with the individual would still be associated with the same individual. Basically checking that they are not messing up the mapping of the _existing_ data. I still think this is important, but as @karawoo said, we can focus on just the specimenIDs for now.

**Comment by kelshmo** [comment]
The PEC use case for checking IDs across studies can be addressed in #257.

**Comment by karawoo** [comment]
@Aryllen am I correct that this issue should be closed now that #382 is merged?

**Comment by Aryllen** [comment]
@karawoo, yes, this should have closed.
