### ISSUE TITLE
Make app configurable for PsychENCODE

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#69]
Right now the process to repurpose the app is:
* Fork the git repo
* Modify the contents of the server and UI functions to
  * Save uploaded files to a different location
  * Customize the checks that are run
  * Customize inputs if needed
* Deploy in a new location on the shiny server

This is doable, but it would be better to make the overall app more configurable. A first step is likely splitting the components into shiny modules (which would be a best practice regardless of whether the app needs to be reused for other projects).

**Comment by kelshmo** [comment]
The PsychENCODE Shiny App will be deployed under my username on the shiny server and our 'repurposed' changes will be implemented on my fork: https://github.com/kelshmo/dccvalidator

**Comment by kelshmo** [comment]
PR #73 adds a module to specify team. 

- [Save uploaded files to a different location](https://github.com/Sage-Bionetworks/dccvalidator/blob/d3ba1726a4f5163878949aff0d2854142545797e/R/app-server.R#L32) I believe could be modularized using this same approach.
