### ISSUE TITLE
Support validating from JSON Schema

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#72]
Needed for PEC and eventually AMP-AD. Look into either using jsonvalidate (R) or reticulate + python package that @cw-dvr8 has been using.

**Comment by kelshmo** [comment]
- [ ] spec required input for dccvalidator
- [ ] @cw-dvr8's python package currently outputs line item notation that could theoretically be converted to a data frame, list or .csv file

**Comment by karawoo** [comment]
> @cw-dvr8's python package currently outputs line item notation that could theoretically be converted to a data frame, list or .csv file

This would be really helpful to have in the `$data` part of a `"check_fail"` object. A named list might be a good output format, as we have a [`show_details()` method](https://github.com/Sage-Bionetworks/dccvalidator/blob/320db4069d2303fa2bde3afea1b1d8096cdcee64/R/app-reporting.R#L79-L84) for this already. I'm imagining a function roughly like this:

```r

check_against_schema <- function(data, schema) {
  result <- {
    # something something here using reticulate to call the python code
  }

  if (result  == 0) { # or however success is indicated
    check_pass(
      msg = "Data is valid against schema.",
      behavior = "Data should conform to the given schema."
    )
  } else {
    check_fail(
      msg = "Data is invalid against schema.",
      behavior = "Data should conform to the given schema.",
      data = convert_results_to_R_data_structure(result) # list of what failed
    )
  }
}
```

There's also the [jsonvalidate](https://github.com/ropensci/jsonvalidate) package, but I'm not sure if it currently gives as much feedback on the nature of the failures as the python package you've been using.

**Comment by karawoo** [comment]
Other conversations in the r channel on slack today have reminded me that synapser doesn't play nicely with reticulate, so we wouldn't be able to wrap the python package to support schema validation unless we were willing to rewrite all of the pieces of the package that interact with synapse to also use reticulate.

**Comment by kelshmo** [comment]
:( :( :( +1000 more sad faces. Lets discuss further.

**Comment by karawoo** [comment]
The [jsonvalidate vignette](https://docs.ropensci.org/jsonvalidate/articles/jsonvalidate.html) has examples of the `verbose` option which does provide more information about the failures -- we should test this with the PEC schemas and see if the information is sufficient.
