### ISSUE TITLE
Metadata files should be present in manifest

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#75]
I've run into this working with collaborators in the past: they don't include the metadata files in the manifest, which sometimes causes confusion and we've needed to go back and track down the files or upload them ourselves from email attachments. We could add a check that all of the metadata files they've uploaded to the app are also present in the `path` column of the manifest.

**Comment by kelshmo** [comment]
Is the best temporary work around to add instructions to the metadata template page? Or add example values in the manifest template? tbh - I didn't even consider this use case!

**Comment by karawoo** [comment]
Yeah, it's not a huge issue, but it does happen. And yes, I think some instructions and/or sample rows on the metadata template would help, like "please list _all_ files to be uploaded, including data files and metadata files."

**Comment by karawoo** [comment]
Bumping this up to medium priority as we're already seeing this arise with data for the AMP-AD release -- people upload the data to staging but not the metadata.
