### ISSUE TITLE
Require additional values for manifest

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#76]
In our last sys bio DCC meeting I believe we agreed to require additional annotations on the manifest that don't appear in the metadata templates (things like consortium, study, grant, fileFormat). I've begun a [template manifest](https://www.synapse.org/#!Synapse:syn20820080) for AMP-AD. `check_cols_manifest()` should be updated to look up a template the way the other ones do.

**Comment by kelshmo** [comment]
We did agree on this!

**Comment by kelshmo** [comment]
should `dataType` and `dataSubtype` be added as required values in the manifest, I *believe* these values to not appear in the metadata template.

**Comment by karawoo** [comment]
They are there (in the manifest template) between `isModelSystem` and `fileFormat`.
