### ISSUE TITLE
App behavior when not signed in to Synapse or not part of a team

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#86]
1. If user is not signed in to Synapse, user can still browse and upload a file without any results. 
2. If user is signed in to Synapse but not a part of a team, the "Not in team" message is displayed grayed out and server session is disconnected. The link to be added to a team is displayed and not clickable.

I think use case 1 is fine as one, or alternatively we could find a way that the message is displayed and it is not possible to click out of it to upload files.

For use case 2, since the link is not clickable, does it make sense to add a URL that is more easily searchable? Alternatively, we could devise another path to a resolution.

**Comment by karawoo** [comment]
@kelshmo can you provide the synapse ID of the user who is not in any teams that you encountered this with? If I try as a user who is not in the right team (but is in a different one), I can click the link. So I think case 2 is a bug that we should definitely fix.

For case 1, I did look into trying to make the modal undismissable and didn't see a quick way, but I'm definitely open to it.

**Comment by karawoo** [comment]
🤦‍♀  this line is still trying to create the folder even though it doesn't have access. I can fix that so the modal is at least visible/clickable and the session doesn't disconnect, but if they try to upload data it will still cause errors.

https://github.com/Sage-Bionetworks/dccvalidator/blob/ba545e1678d630240af7b83df863b612444ef162/R/app-server.R#L24-L28

**Comment by kelshmo** [comment]
@karawoo App behavior still disconnects from the server if the user is not certified - though there is about 10 seconds the "Not a team member" links could be clickable.

**Comment by karawoo** [comment]
@kelshmo I can't reproduce, do you have logs I could look at?

**Comment by kelshmo** [comment]
I confirmed PR #92 is pulled into my fork. The server is still disconnecting after about 10 seconds.

**Comment by kelshmo** [comment]
This issue was fixed by managing Permission sharing on Synapse for the annotation module and validation folder.
