### ISSUE TITLE
Add support for new metadata templates

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#90]
WGS, WES, nanostring, single cell RNA seq, and possibly others are expected for November.

Need to add support for these once they have been shared in https://www.synapse.org/#!Synapse:syn18512044

**Comment by karawoo** [comment]
Meagan is working on nanostring, we'll reuse PEC templates for single cell RNAseq and WGS (which will be the same template as WES)

**Comment by karawoo** [comment]
For November we will also have behavioral data, electrophysiology. Unsure if we will have metadata templates for these. If no templates, we should add these assays to the assay dropdown and, if selected, hide the assay metadata upload.

**Comment by Aryllen** [comment]
Started the branch for this change. Just waiting on the templates.

**Comment by karawoo** [comment]
Added the single cell RNA seq template and WGS templates:
- https://www.synapse.org/#!Synapse:syn21018360
- https://www.synapse.org/#!Synapse:syn21018358

**Comment by Aryllen** [comment]
Un-assigning self for now simply because these are relatively simple changes to make now that we have the config file. That said, we should still add the templates that we have currently available.
