### ISSUE TITLE
Figure out which columns need to be complete

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#91]
As a possible stopgap before #72 we need to figure out which if any columns in the metadata and manifest must be complete (i.e. no missing values). I say this is a stopgap because the conditional logic in JSON Schema will cover this, but given the problem of using the Python validation library + synapser, this will take some time to implement.

**Comment by karawoo** [comment]
Let's add a function `check_cols_complete()` (similar to `check_cols_empty()`) that checks if a column is complete and returns `check_fail` if not. I'm not sure yet which columns we will want to run this check on for AMP-AD, but we can write the function now and add it to the suite of validators once we know.

**Comment by Aryllen** [comment]
Given that the `check_cols_complete()` function is based on `check_cols_empty()`, it has the `strict = FALSE` parameter and default. Since this would only give a warning if the columns were not complete, would you prefer the `strict` default to be `TRUE`?

**Comment by karawoo** [comment]
Yes, I think `strict = TRUE` is a better default in this case

**Comment by karawoo** [comment]
Reopening this as we still need to decide which columns to run this check on. Probably at least all individualID and specimenID columns in the metadata files (but not the manifest, because of possible multi-specimen files). Maybe others as well.

**Comment by karawoo** [comment]
Manifest:
- consortium
- study
- grant
- fileFormat
- parent (even though they won't have access yet)

Individual:
- individualID

Biospecimen:
- individualID
- specimenID

Assay: 
- specimenID
