### ISSUE TITLE
Document all customizations required to repurpose the app

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#94]
Vignette (or something) that describes the specific customizations one would need to reuse the app in a different consortium (until it is more configurable).

**Comment by karawoo** [comment]
Jotting down known ones here from my whiteboard for now:
- synID of folder to store files
- location of templates (individual, biospecimen, assay, manifest)
- list of study names
- team ID
- links in instructions to annotation definitions
- list of assays in UI
- any customizations to which `check_*()` functions are run

In future:
- specimen/individual ID table

**Comment by kelshmo** [comment]
Here are the notes I have generated so far. 

- Replace instructions link to annotation dictionary in [app-server.R](https://github.com/Sage-Bionetworks/dccvalidator/blob/ecb7389866dad155b825aa436db02a1c050efc22/R/app-server.R#L130)
- Replace Team ID in [app-server.R](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/app-server.R#L22)
- Replace folder to upload to in [app-server.R](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/app-server.R#L30)
- Replace annotation schema in [app-server.R](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/app-server.R#L46), [check-annotation-keys.R](https://github.com/Sage-Bionetworks/dccvalidator/blob/c6a37daa16f6ddac23929a818fbf44efbceb0fca/R/check-annotation-keys.R#L157) and [check-annotation-values.R](https://github.com/Sage-Bionetworks/dccvalidator/blob/9de8220498d1e0c465b9ba2a878092c660be9091/R/check-annotation-values.R#L261)
- Model validation folder permissions off of [this code](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/inst/app/create_project.R)
- Customize [assay types vector](https://github.com/Sage-Bionetworks/dccvalidator/blob/fdf6d2cf3587d80e4e420557a8c425ef38850dcc/R/check-col-names.R#L107) 
- Customize [synIDs to templates](https://github.com/Sage-Bionetworks/dccvalidator/blob/fdf6d2cf3587d80e4e420557a8c425ef38850dcc/R/check-col-names.R#L110)
- Customize study table [using AMP-AD Studies Table](https://www.synapse.org/#!Synapse:syn11363298/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjExMzYzMjk4IiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0Ijo1MCwgImxpbWl0IjoyNX0=) 
  - Replace synID pointing to Studies table

**Comment by kelshmo** [comment]
I think this is complete if comments from #123 are added to the README and details of the required columns are noted.

**Comment by karawoo** [comment]
@kelshmo I think this is worthy of its own article on the pkgdown site. Do you mind if I start a draft?

**Comment by kelshmo** [comment]
I do not mind!
